/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:clockbuttons:411693:
  appc.background(230);
} //_CODE_:clockbuttons:411693:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:688102:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:688102:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:525657:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:525657:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:927728:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:927728:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:784516:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:784516:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:530479:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:custom_slider1:530479:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  clockbuttons = GWindow.getWindow(this, "Window title", 0, 0, 400, 300, JAVA2D);
  clockbuttons.noLoop();
  clockbuttons.setActionOnClose(G4P.KEEP_OPEN);
  clockbuttons.addDrawHandler(this, "win_draw1");
  button1 = new GButton(clockbuttons, 24, 195, 80, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(clockbuttons, 115, 201, 80, 30);
  button2.setText("Face text");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(clockbuttons, 209, 202, 80, 30);
  button3.setText("Face text");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(clockbuttons, 309, 204, 80, 30);
  button4.setText("Face text");
  button4.addEventHandler(this, "button4_click1");
  custom_slider1 = new GCustomSlider(clockbuttons, 56, 130, 300, 40, "grey_blue");
  custom_slider1.setLimits(0.5, 0.0, 1.0);
  custom_slider1.setNbrTicks(60);
  custom_slider1.setStickToTicks(true);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 1);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  clockbuttons.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow clockbuttons;
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GCustomSlider custom_slider1; 
