/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:898850:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:898850:

public void addTask_change1(GTextField source, GEvent event) { //_CODE_:addTask:757427:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:addTask:757427:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  textfield1 = new GTextField(this, 170, 145, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  addTask = new GTextField(this, 200, 400, 400, 30, G4P.SCROLLBARS_NONE);
  addTask.setOpaque(true);
  addTask.addEventHandler(this, "addTask_change1");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GTextField addTask; 
